### Today Objective:

* Numpy

In [1]:
import numpy as np
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [2]:
a=np.array((10,20,30,40,50))
a

array([10, 20, 30, 40, 50])

In [3]:
a=np.array({10,20,30,40,50})
a

array({40, 10, 50, 20, 30}, dtype=object)

In [13]:
a=np.array([10,20,30,40,50])
print("numpy array is:",a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

numpy array is: [10 20 30 40 50]
array shape is: (5,)
array length is: 5
dimentions of array is:  1
type of array is:  int32


In [14]:
a=np.array([10.3,20.5,30.7,40.9,50.99,23.5])
print("numpy array is:",a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

numpy array is: [10.3  20.5  30.7  40.9  50.99 23.5 ]
array shape is: (6,)
array length is: 6
dimentions of array is:  1
type of array is:  float64


In [15]:
a=np.array([10,20,30.7,40,50.99,23])
print("numpy array is:",a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

numpy array is: [10.   20.   30.7  40.   50.99 23.  ]
array shape is: (6,)
array length is: 6
dimentions of array is:  1
type of array is:  float64


In [16]:
a=np.array(["a","b","c"])
print("numpy array is:",a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

numpy array is: ['a' 'b' 'c']
array shape is: (3,)
array length is: 3
dimentions of array is:  1
type of array is:  <U1


In [17]:
a=np.array(["a","b","c",10,20,30,40])
print("numpy array is:",a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

numpy array is: ['a' 'b' 'c' '10' '20' '30' '40']
array shape is: (7,)
array length is: 7
dimentions of array is:  1
type of array is:  <U2


In [18]:
a=np.array(["a","b","c",10,20,30,40,12.4,34.5])
print("numpy array is:",a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

numpy array is: ['a' 'b' 'c' '10' '20' '30' '40' '12.4' '34.5']
array shape is: (9,)
array length is: 9
dimentions of array is:  1
type of array is:  <U4


In [19]:
a=np.array(["a","b","c",10,20,30,40,12.4,34.5,True,False])
print("numpy array is:",a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

numpy array is: ['a' 'b' 'c' '10' '20' '30' '40' '12.4' '34.5' 'True' 'False']
array shape is: (11,)
array length is: 11
dimentions of array is:  1
type of array is:  <U5


In [20]:
a=np.array(["a","b","c",10,20,30,40,12.4,34.5,True,False,3+2j])
print("numpy array is:",a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

numpy array is: ['a' 'b' 'c' '10' '20' '30' '40' '12.4' '34.5' 'True' 'False' '(3+2j)']
array shape is: (12,)
array length is: 12
dimentions of array is:  1
type of array is:  <U6


In [21]:
a=np.array([True,False,True,False])
print("numpy array is:",a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

numpy array is: [ True False  True False]
array shape is: (4,)
array length is: 4
dimentions of array is:  1
type of array is:  bool


In [22]:
a=np.array([3+2j,4+7j,5+3j])
print("numpy array is:",a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

numpy array is: [3.+2.j 4.+7.j 5.+3.j]
array shape is: (3,)
array length is: 3
dimentions of array is:  1
type of array is:  complex128


* 1D array => Vector
* 2D array => Matrix
* 3D,4D,5D.....nd  => Multi Dimentional

In [25]:
# 2d array => list->list:
a=np.array([[10,20],[30,40],[50,60]])
print(a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

[[10 20]
 [30 40]
 [50 60]]
array shape is: (3, 2)
array length is: 3
dimentions of array is:  2
type of array is:  int32


In [26]:
a=np.array([[10,20,45],[30,40,20],[50,60,70]])
print(a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

[[10 20 45]
 [30 40 20]
 [50 60 70]]
array shape is: (3, 3)
array length is: 3
dimentions of array is:  2
type of array is:  int32


In [28]:
# 3d array => list->list->list
a=np.array([[[10,20],[30,40]]])
print(a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

[[[10 20]
  [30 40]]]
array shape is: (1, 2, 2)
array length is: 1
dimentions of array is:  3
type of array is:  int32


In [31]:
# list
l=range(100)

In [32]:
# numpy
a=np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [33]:
# normal list
l=range(1000)
%timeit [i**2 for i in l]

646 µs ± 110 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [34]:
l=np.arange(1000)
%timeit [i**2 for i in l]

506 µs ± 10.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Type conversions:

In [37]:
a=np.array([10,20,30,40,50],dtype=float)
print(a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

[10. 20. 30. 40. 50.]
array shape is: (5,)
array length is: 5
dimentions of array is:  1
type of array is:  float64


In [38]:
a=np.array([10.33,20.2,30.4,40.9,50.77],dtype=int)
print(a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

[10 20 30 40 50]
array shape is: (5,)
array length is: 5
dimentions of array is:  1
type of array is:  int32


In [39]:
a=np.array([10,20,30,40],dtype=complex)
print(a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

[10.+0.j 20.+0.j 30.+0.j 40.+0.j]
array shape is: (4,)
array length is: 4
dimentions of array is:  1
type of array is:  complex128


In [40]:
a=np.array([10,20,30,40],dtype=bool)
print(a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

[ True  True  True  True]
array shape is: (4,)
array length is: 4
dimentions of array is:  1
type of array is:  bool


In [41]:
a=np.array([10,20,30,40,0,0,-23,-56,560],dtype=bool)
print(a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

[ True  True  True  True False False  True  True  True]
array shape is: (9,)
array length is: 9
dimentions of array is:  1
type of array is:  bool


In [43]:
a=np.array([True,False,True],dtype=int)
print(a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

[1 0 1]
array shape is: (3,)
array length is: 3
dimentions of array is:  1
type of array is:  int32


In [44]:
a=np.array([10,20,30,40,0,0,-23,-56,560,"string"],dtype=bool)
print(a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

[ True  True  True  True False False  True  True  True  True]
array shape is: (10,)
array length is: 10
dimentions of array is:  1
type of array is:  bool


In [53]:
a=np.array(["a","b","c","string","0","9"],dtype=bool)
print(a)
print("array shape is:",a.shape)
print("array length is:",len(a))
print("dimentions of array is: ",a.ndim)
print("type of array is: ",a.dtype)

[ True  True  True  True  True  True]
array shape is: (6,)
array length is: 6
dimentions of array is:  1
type of array is:  bool


### Change the dimentions

In [45]:
a=np.array([10,20,30,40])
print(a)
print("dimentions of array is: ",a.ndim)

[10 20 30 40]
dimentions of array is:  1


In [46]:
a=np.array([10,20,30,40],ndmin=2)
print(a)
print("dimentions of array is: ",a.ndim)

[[10 20 30 40]]
dimentions of array is:  2


In [49]:
a=np.array([10,20,30,40],ndmin=3)
print(a)
print("dimentions of array is: ",a.ndim)

[[[10 20 30 40]]]
dimentions of array is:  3
